TOPIC_KEYWORDS: dict[str, list[str]] = {
    "Artificial Intelligence": ["artificial intelligence", "ai ", "algorithm"],
    "Agriculture": ["farm", "agriculture", "snap", "food", "nutrition", "crop"],
    "Civil Rights": ["civil rights", "discrimination", "equal protection", "accessibility"],
    "Commerce": ["commerce", "trade", "tariff", "supply chain", "manufacturing"],
    "Crime & Justice": ["crime", "criminal", "sentencing", "police", "law enforcement"],
    "Disaster & Emergency": ["disaster", "emergency", "fema", "wildfire", "hurricane"],
    "Education": ["education", "school", "student", "teacher", "college", "university"],
    "Elections": ["election", "voter", "voting", "ballot", "registration"],
    "Environment": ["environment", "clean air", "clean water", "conservation", "wildlife"],
    "Healthcare": ["health", "medicare", "medicaid", "hospital"],
    "Housing": ["housing", "mortgage", "rent"],
    "Immigration": ["immigration", "border", "citizenship", "asylum"],
    "Labor": ["labor", "worker", "workforce", "union", "wage", "employment"],
    "Energy": ["energy", "grid", "electric", "oil", "gas"],
    "Defense": ["defense", "military", "armed forces"],
    "Foreign Affairs": ["foreign", "diplomacy", "sanction", "treaty", "international"],
    "Government Operations": ["federal agency", "oversight", "government", "administrative"],
    "Public Lands": ["public lands", "national park", "forest service", "blm land"],
    "Science & Space": ["science", "research", "nasa", "space", "innovation"],
    "Social Services": ["social security", "child care", "welfare", "family assistance"],
    "Tax & Budget": ["tax", "appropriation", "budget", "revenue", "spending"],
    "Technology": ["technology", "cyber", "semiconductor", "broadband"],
    "Transportation": ["transportation", "highway", "rail", "transit", "aviation"],
    "Veterans": ["veteran", "va ", "servicemember"],
    "Privacy": ["privacy", "data protection", "surveillance"],
}

DEFAULT_MONITORING_TOPICS = ",".join(TOPIC_KEYWORDS)
